export const subCategoryIdTranslationsMap = new Map<number, string>([
  [1, "Fruits et Légumes"],
  [2, "Produits Laitiers"],
  [3, "Viandes et Poissons"],
  [4, "Boulangerie et Pâtisserie"],
  [5, "Épicerie Salée"],
  [6, "Épicerie Sucrée"],
  [7, "Boissons"],
  [8, "Surgelés"],
  [9, "Produits Bio"],
  [10, "Produits Sans Gluten"],
  [11, "Charcuterie"],
  [12, "Condiments et Sauces"],
  [13, "Snacks et Apéritifs"],
  [14, "Petit-Déjeuner et Céréales"],
  [15, "Plats Cuisinés"],
  [16, "Pâtes, Riz et Légumineuses"],
  [17, "Produits d'Hygiène"],
  [18, "Produits d'Entretien"],
  [19, "Animaux"],
]);
