export const subCategoryIdTranslationsMap = new Map<number, string>([
  [1, 'Produits laitiers'],
  [2, 'Œufs'],
  [3, 'Fromages'],
  [4, 'Fruits'],
  [5, 'Légumes'],
  [6, 'Boucherie'],
  [7, 'Volaille'],
  [8, 'Poissonnerie'],
  [9, 'Charcuterie'],
  [10, 'Pain'],
  [11, 'Pâtisserie'],
  [12, 'Épicerie sucrée'],
  [13, 'Épicerie salée'],
  [14, 'Eaux'],
  [15, 'Jus'],
  [16, 'Soda'],
  [17, 'Thés glacés'],
  [18, 'Vins'],
  [19, 'Bières'],
  [20, 'Alcools'],
  [21, 'Hygiène'],
  [22, 'Beauté'],
  [23, 'Entretien de la maison'],
  [24, 'Accessoires de la maison'],
  [25, 'Bébé'],
  [26, 'Animalerie'],
  [27, 'Produits du monde'],
  [28, 'Produits de nos régions'],
  [29, 'Bio'],
  [30, 'Nutrition'],
  [31, 'Jardin'],
  [32, 'Auto'],
  [33, 'Bricolage'],
  [34, 'Jouets'],
  [35, 'Jeux vidéo'],
  [36, 'Livres'],
  [37, 'High-tech'],
  [38, 'Téléphonie'],
  [39, 'Électroménager'],
  [40, 'Cuisine'],
  [41, 'Meuble'],
  [42, 'Linge de maison'],
  [43, 'Mode'],
  [44, 'Bijoux'],
  [45, 'Bagagerie'],
  [46, 'Puériculture'],
  [47, 'Billetterie'],
  [48, 'Voyage'],
]);
